### ISSUE TITLE
PORT ändern

### ISSUE THREAD

**Issue by PhilippIvan** [hannes-ma/orderjutsu-docker#1]
Hallo,

ist es möglich den Port auf 80 zu ändern oder muss es 8080 sein??

Lg

Philipp

**Comment by hannes-ma** [comment]
Ja, kann man ändern. In der docker-compose.yml für nginx den Port von 8080 auf 80 ändern:

`ports:
      - "80:8080"`

**Comment by PhilippIvan** [comment]
Hallo, Danke für die Prompte antwort hat super funktioniert.

DANKESCHÖN
